### ISSUE TITLE
error occurs when .py declared ' utf-8 ' but sys.stdin.encoding == GBK

### ISSUE THREAD

**Issue by umialpha** [evanplaice/pypreprocessor#17]
I am writing .py on windows platform, and all the .py are declared with 'utf-8' format where sys.stdin.encoding == 'GBK'.
when exec(f.read()) , trace occurs as follows:
SyntaxError: encoding declaration in Unicode string

**Comment by hendiol** [comment]
Hi @roylee1314 ,

i think you have to possibilities:
-  change `sys.stdin.encoding` to `utf-8`
-  change this line https://github.com/interpreters/pypreprocessor/blob/5e8400a306252e0e0f7546fbcc656794bad7300a/pypreprocessor/__init__.py#L28 to `self.readEncoding = 'utf-8'`

Edit: The second option is also stated in the Readme.md

@evanplaice @Epikem should this error be catched/handled by pypreprocessor?

**Comment by hendiol** [comment]
As I saw no the `self.readEnconding` is mentioned in the ReadMe.md so its an option.

More generall should we think about an config file?

**Comment by Epikem** [comment]
Is this package caused the error? Maybe below is similar problem :
https://stackoverflow.com/questions/39142304/syntaxerror-encoding-declaration-in-unicode-string

**Comment by umialpha** [comment]
thx guys. I will try it~
