### ISSUE TITLE
Issues installing with pip

### ISSUE THREAD

**Issue by cyclicredundancy** [evanplaice/pypreprocessor#18]
I am trying to install pypreprocessor on windows and hitting the following error:
The temp directory listed below gets cleared so I was not able to peek into it.
Also I am able to successfully install other python modules.

Apologies if this is the wrong place to report these bugs!

```
Collecting pypreprocessor
  Using cached pypreprocessor-0.7.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXX\AppData\Local\Temp\pip-build-wofa1f2t\pypreprocessor\setup.py", line 16, in <module>
        from tests import RunTests
      File "C:\Users\XXXX\AppData\Local\Temp\pip-build-wofa1f2t\pypreprocessor\tests\__init__.py", line 11, in <module>
        from tests import maintest
    ImportError: cannot import name 'maintest'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XXXX\AppData\Local\Temp\pip-build-wofa1f2t\pypreprocessor\

```

**Comment by hendiol** [comment]
Hi @cyclicredundancy , 

for this issue #18 a pull-request already exits: #15. Please have a look there.
We need the owner @evanplaice to merge it. May I found a temporary solution.

Regards Hendiol

**Comment by cyclicredundancy** [comment]
Thanks! I will close this issue as a duplicate then.
