### ISSUE TITLE
Exception has occcurred: IndexError

### ISSUE THREAD

**Issue by s0564896** [evanplaice/pypreprocessor#28]
Exception has occurred: IndexError
list index out of range
pypreprocessor.parse()
What does this exception mean?
I created several lists (this one has  about 300 entries) and used #defines to shorten them a bit if necessary.
Some lists contain more than 600 elements and there is no complication at all.

**Comment by s0564896** [comment]
The error seems to occur at an #else directive
self._ifblocks[-1] = not self._if(blocks[-1] ( ~line 170) in the pypreprocessor source file
What could be the error?

**Comment by elrandira** [comment]
that would mean you have more #else than active #if blocks?
