### ISSUE TITLE
Doesn't work with pserve

### ISSUE THREAD

**Issue by Kostanos** [evanplaice/pypreprocessor#7]
Running simple code under pserve and got this error:

`
OSError: [Errno 2] No such file or directory: 'tmp_pservec'
`

```
import sys
from pypreprocessor import pypreprocessor

# this is temporary workaround for mesuma which runs on python 2.7 and for some reason
# always includes this code
print(sys.version_info.major)
#exclude
if sys.version_info.major >= 3:
    pypreprocessor.defines.append('python3')
else:
    pypreprocessor.defines.append('python2')

pypreprocessor.parse()
#endexclude

#ifdef python3
print('python3')
#ifdef python3
print('python2')
#endif
```

**Comment by evanplaice** [comment]
Not sure why your workaround works. Either way, the #exclude should come after pypreprocessor.parse().

Either way, all preprocessor directives should happen after the pypreprocessor.parse() call. The reason being, the processor is self consuming. The python code runs as normal python code until the parse() command is found, picks up after the parse() command parsing any preprocessor directives, then reloads and executes the output.
